//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBlogs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Blog_Master
    {
        public int Food_Blog_Master_Id { get; set; }
        public string Food_Blog_Post_Unique_Id { get; set; }
        public string Food_Blog_Post_Title { get; set; }
        public System.DateTime Created_Post_Date { get; set; }
    }
}
