//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBlogs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodBlogEntities : DbContext
    {
        public FoodBlogEntities()
            : base("name=FoodBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Food_Comments> Food_Comments { get; set; }
        public virtual DbSet<Post_Visit_Count> Post_Visit_Count { get; set; }
        public virtual DbSet<Post_Visit_Count_History> Post_Visit_Count_History { get; set; }
        public virtual DbSet<Food_Blog_Master> Food_Blog_Master { get; set; }
    }
}
