//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBlogs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Comments
    {
        public int Food_Comments_Id { get; set; }
        public string Food_Comment_Description { get; set; }
        public string Food_Comment_Email_id { get; set; }
        public string Food_Comment_Page { get; set; }
        public string Food_Comment_User_Name { get; set; }
    }
}
