//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBlogs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Visit_Count_History
    {
        public int Post_Visit_Count_History_Id { get; set; }
        public string Post_Name { get; set; }
        public System.DateTime Post_Date { get; set; }
    }
}
